import Head from 'next/head';
import React, { useContext } from 'react';
import MouseContext from '../contexts/mouse-context';
import CloudLoader from './CloudLoader';
import Cursor from './Cursor';
import HomepageLink from './HomepageLink';
import { NakiskaLogoSvg } from './IconComponents';
import VideoPlayer from './VideoPlayer';
import { MouseProvider } from '../contexts/mouse-context';

export default function Layout(props: { children: React.ReactNode }) {
  const contextState = useContext(MouseContext);
  return (
    <CloudLoader>
      <Head>
        <title>Spiral Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0"></meta>
      </Head>

      <Cursor />
      <div className="flex h-full min-h-[100dvh] grow flex-col items-center overflow-scroll bg-white p-8">
        <div
          onClick={contextState.mouseClickEvent}
          className="absolute top-0 left-0 right-0 bottom-0 z-0"></div>
        <main className="flex h-full w-full grow flex-col items-center overflow-hidden bg-black">
          <nav className="flex w-full justify-between">
            <HomepageLink
              title={
                <NakiskaLogoSvg classGroup="mb-2" className="transition group-hover:fill-red-500" />
              }
              href="/"
            />

            <HomepageLink title="contact" href="/contact" />
          </nav>
          <section className="flex h-full w-full grow items-center justify-center">
            {props.children}
          </section>
          <footer className="flex w-full justify-between">
            <HomepageLink title="services" href="/services" />
            <HomepageLink title="clients" href="/clients" />
          </footer>
        </main>
        {contextState.fullScreenVideo ? <VideoPlayer /> : null}
      </div>
    </CloudLoader>
  );
}
